# Generated by Django 3.1.7 on 2021-04-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0003_auto_20210407_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='status',
            new_name='status_departmnet',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='status_employee',
        ),
    ]
